# -*- coding: utf-8 -*-
"""
Main script to generate semantic layer for 10 random APIs from 12306 project
"""
import sys
import random
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent))

from java_api_analyzer import JavaAPIAnalyzer, generate_api_semantic_layer


def main():
    """Main function"""
    print("=" * 60)
    print("12306 Project - API Semantic Layer Generator")
    print("=" * 60)

    # Find all controller files
    project_root = Path("F:/12306")
    controller_files = list(project_root.glob("**/controller/*.java"))

    print(f"\n[INFO] Found {len(controller_files)} controller files")

    # Analyze all controllers and collect APIs
    all_apis = []

    for controller_file in controller_files:
        try:
            analyzer = JavaAPIAnalyzer(str(controller_file))
            result = analyzer.analyze()

            for api in result['apis']:
                all_apis.append({
                    'api': api,
                    'controller': result['controller'],
                    'file_path': result['file_path']
                })

        except Exception as e:
            print(f"[WARN] Failed to analyze {controller_file.name}: {e}")

    print(f"[INFO] Total APIs found: {len(all_apis)}")

    # Randomly select 10 APIs
    if len(all_apis) < 10:
        print(f"[WARN] Only {len(all_apis)} APIs available, using all")
        selected_apis = all_apis
    else:
        selected_apis = random.sample(all_apis, 10)

    print(f"\n[INFO] Selected {len(selected_apis)} APIs for analysis")
    print("=" * 60)

    # Generate semantic layer for each API
    output_dir = Path("F:/semantic_layer_project/output/12306_apis")
    output_dir.mkdir(parents=True, exist_ok=True)

    for idx, api_data in enumerate(selected_apis, 1):
        api = api_data['api']
        controller = api_data['controller']
        file_path = api_data['file_path']

        print(f"\n[{idx}/10] Generating semantic layer for: {api['method_name']}")
        print(f"       URL: {api['http_method']} {api['url']}")

        # Generate markdown
        md_content = generate_api_semantic_layer(api, controller, file_path)

        # Save to file
        output_file = output_dir / f"{idx:02d}_{api['method_name']}.md"
        output_file.write_text(md_content, encoding='utf-8')

        print(f"       [OK] Saved to: {output_file.name}")

    print("\n" + "=" * 60)
    print(f"[SUCCESS] Generated {len(selected_apis)} semantic layer documents")
    print(f"[OUTPUT] Directory: {output_dir}")
    print("=" * 60)

    # Generate summary
    summary_file = output_dir / "00_SUMMARY.md"
    summary_content = generate_summary(selected_apis)
    summary_file.write_text(summary_content, encoding='utf-8')

    print(f"\n[INFO] Summary saved to: {summary_file.name}")


def generate_summary(selected_apis: list) -> str:
    """Generate summary document"""
    md = """# 12306 Project - API Semantic Layer Summary

> Generated API semantic layer documents for 10 randomly selected APIs

---

## Selected APIs

"""

    for idx, api_data in enumerate(selected_apis, 1):
        api = api_data['api']
        controller = api_data['controller']

        md += f"""
### {idx}. {api['method_name']}

- **Controller**: {controller['name']}
- **Description**: {api['comment']}
- **HTTP Method**: {api['http_method']}
- **URL**: `{api['url']}`
- **Document**: `{idx:02d}_{api['method_name']}.md`

"""

    md += """
---

## Statistics

"""

    # Count by HTTP method
    get_count = sum(1 for api_data in selected_apis if api_data['api']['http_method'] == 'GET')
    post_count = sum(1 for api_data in selected_apis if api_data['api']['http_method'] == 'POST')

    md += f"""
- **Total APIs**: {len(selected_apis)}
- **GET APIs**: {get_count}
- **POST APIs**: {post_count}

---

## Business Domains

"""

    # Count by domain
    domains = {}
    for api_data in selected_apis:
        file_path = api_data['file_path'].lower()
        if 'order' in file_path:
            domain = 'Order Management'
        elif 'ticket' in file_path:
            domain = 'Ticket Management'
        elif 'user' in file_path:
            domain = 'User Management'
        elif 'pay' in file_path:
            domain = 'Payment Management'
        else:
            domain = 'Other'

        domains[domain] = domains.get(domain, 0) + 1

    for domain, count in sorted(domains.items(), key=lambda x: x[1], reverse=True):
        md += f"- **{domain}**: {count} APIs\n"

    md += """

---

*Generated by AI Agent Semantic Layer System for Java*
"""

    return md


if __name__ == '__main__':
    main()
