# -*- coding: utf-8 -*-
"""
Markdown Generator - Generate semantic layer documentation
"""
from typing import Dict, Any
from datetime import datetime


class MarkdownGenerator:
    """Markdown Generator"""

    def generate(
        self,
        semantic_data: Dict[str, Any],
        behavior_data: Dict[str, Any],
        context_data: Dict[str, Any],
        repo_info: Dict[str, str]
    ) -> str:
        """Generate Markdown document"""
        sections = []

        # Header
        sections.append(self._generate_header(repo_info))

        # TOC
        sections.append(self._generate_toc())

        # Part 1: Semantic Layer
        sections.append(self._generate_semantic_layer(semantic_data))

        # Part 2: Behavior Layer
        sections.append(self._generate_behavior_layer(behavior_data))

        # Part 3: Context Layer
        sections.append(self._generate_context_layer(context_data))

        # Appendix
        sections.append(self._generate_appendix(semantic_data, behavior_data))

        return '\n\n'.join(sections)

    def _generate_header(self, repo_info: Dict[str, str]) -> str:
        """Generate document header"""
        header = f"""# Semantic Layer - {repo_info['name']}

> Auto-generated by AI Agent Semantic Layer System
>
> Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
>
> Repository: `{repo_info['path']}`

---

## Usage Guide

This document is the **semantic layer** of the codebase, designed to help AI Agents understand business semantics, execution behavior, and coding conventions.

### How to Use

1. **Understand Business Domains**: Check "Business Domains" section
2. **Find Code Entities**: Search in "Code Entity Semantics"
3. **Understand Execution**: Check "Execution Patterns"
4. **Follow Conventions**: Refer to "Coding Constraints"
5. **Learn from Examples**: Check "Code Examples"

### Confidence Levels

- **0.9-1.0**: High confidence (based on explicit code structure)
- **0.7-0.9**: Medium confidence (based on naming patterns)
- **0.5-0.7**: Low confidence (needs verification)
- **< 0.5**: Uncertain (reference only)"""
        return header

    def _generate_toc(self) -> str:
        """Generate table of contents"""
        return """## Table of Contents

- [Part 1: Semantic Layer](#part-1-semantic-layer)
  - [Business Domains](#business-domains)
  - [Code Entity Semantics](#code-entity-semantics)
- [Part 2: Behavior Layer](#part-2-behavior-layer)
  - [Execution Patterns](#execution-patterns)
  - [Side Effects](#side-effects)
- [Part 3: Context Layer](#part-3-context-layer)
  - [Coding Constraints](#coding-constraints)
  - [Code Examples](#code-examples)
- [Appendix](#appendix)
  - [Statistics](#statistics)"""

    def _generate_semantic_layer(self, semantic_data: Dict[str, Any]) -> str:
        """Generate semantic layer section"""
        sections = [
            "---",
            "# Part 1: Semantic Layer",
            "",
            "> Goal: Help AI Agent understand 'what the code is'",
            "",
            "## Business Domains",
            ""
        ]

        # Business domains
        for domain in semantic_data['domains']:
            sections.append(f"### {domain['name']}")
            sections.append(f"- **Description**: {domain['description']}")
            sections.append(f"- **Members**: {len(domain['members'])}")
            sections.append("")

        sections.append("## Code Entity Semantics")
        sections.append("")

        # Group entities by domain
        entities_by_domain = {}
        for entity in semantic_data['entities']:
            domain = entity.get('business_domain', 'Unknown')
            if domain not in entities_by_domain:
                entities_by_domain[domain] = []
            entities_by_domain[domain].append(entity)

        for domain, entities in entities_by_domain.items():
            sections.append(f"### {domain}")
            sections.append("")

            for entity in entities[:5]:  # Max 5 per domain
                sections.append(f"#### {entity['kind']}: `{entity['name']}`")
                sections.append(f"- **Semantic Role**: {entity['semantic_role']}")
                sections.append(f"- **Responsibility**: {entity['responsibility']}")
                sections.append(f"- **Location**: `{entity['file_path']}:{entity['start_line']}`")
                sections.append(f"- **Confidence**: {entity['confidence']:.2f}")
                sections.append("")

        return '\n'.join(sections)

    def _generate_behavior_layer(self, behavior_data: Dict[str, Any]) -> str:
        """Generate behavior layer section"""
        sections = [
            "---",
            "# Part 2: Behavior Layer",
            "",
            "> Goal: Help AI Agent understand 'what the code does'",
            "",
            "## Execution Patterns",
            ""
        ]

        # Execution patterns
        for pattern in behavior_data['patterns']:
            sections.append(f"### {pattern['type']}: `{pattern['entry_point']}`")
            sections.append(f"- **Description**: {pattern['description']}")
            sections.append(f"- **Location**: `{pattern['file_path']}:{pattern['line']}`")
            sections.append("")

        sections.append("## Side Effects")
        sections.append("")

        # Side effects
        side_effects_by_type = {}
        for effect in behavior_data['side_effects']:
            effect_type = effect['type']
            if effect_type not in side_effects_by_type:
                side_effects_by_type[effect_type] = []
            side_effects_by_type[effect_type].append(effect)

        for effect_type, effects in side_effects_by_type.items():
            sections.append(f"### {effect_type}")
            sections.append("")
            for effect in effects[:5]:  # Max 5 per type
                sections.append(f"- **{effect['symbol']}**: {effect['description']} (Risk: {effect['risk_level']})")
            sections.append("")

        return '\n'.join(sections)

    def _generate_context_layer(self, context_data: Dict[str, Any]) -> str:
        """Generate context layer section"""
        sections = [
            "---",
            "# Part 3: Context Layer",
            "",
            "> Goal: Provide task-relevant context for AI Agent",
            "",
            "## Coding Constraints",
            ""
        ]

        # Constraints
        for constraint in context_data['constraints']:
            sections.append(f"### {constraint['type'].replace('_', ' ').title()}")
            sections.append(f"- **Description**: {constraint['description']}")
            sections.append(f"- **Enforcement**: {constraint['enforcement']}")
            if 'examples' in constraint:
                sections.append("- **Examples**:")
                for example in constraint['examples']:
                    sections.append(f"  - {example}")
            if 'details' in constraint:
                sections.append(f"- **Details**: {constraint['details']}")
            sections.append("")

        sections.append("## Code Examples")
        sections.append("")

        # Examples
        for example in context_data['examples']:
            sections.append(f"### {example['title']}")
            sections.append(f"- **Symbol**: `{example['symbol']}`")
            sections.append(f"- **Location**: `{example['file_path']}:{example['line']}`")
            sections.append(f"- **Description**: {example['description']}")
            sections.append("")

        return '\n'.join(sections)

    def _generate_appendix(self, semantic_data: Dict, behavior_data: Dict) -> str:
        """Generate appendix"""
        return f"""---
# Appendix

## Statistics

- **Business Domains**: {len(semantic_data['domains'])}
- **Code Entities**: {len(semantic_data['entities'])}
- **Execution Patterns**: {len(behavior_data['patterns'])}
- **Side Effects**: {len(behavior_data['side_effects'])}

## Update Guidelines

Regenerate this document when:
- Adding new feature modules
- Refactoring code architecture
- Monthly maintenance updates

## Feedback

If semantic information is inaccurate:
1. Check code comments
2. Ensure naming follows conventions
3. Manually correct this document
4. Re-run the generator

---

*Generated by AI Agent Semantic Layer System*"""
